Bugfix/all 4863 doge getblock
tatumio/tatum-js pull request #1067
Opened 2024-02-20 08:37 UTC by rostislavjadavan

# Description

Doge `getBlock` method has different type of `verbosity` param then other UTXO based chains.
See:
https://github.com/dogecoin/dogecoin/blob/3a29ba6d497cd1d0a32ecb039da0d35ea43c9c85/src/rpc/blockchain.cpp#L741

Fixes # (issue)

- ALL-4863

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-02-20 08:38 UTC, Hathoriel commented
upgrade package json and changelog

2024-02-20 08:39 UTC, Hathoriel requested changes

2024-02-20 08:43 UTC, rostislavjadavan commented on src/service/rpc/utxo/DogeRpc.ts
> +export class DogeRpc extends AbstractDogeRpc implements DogeRpcSuite {
Could you be more specific, what is not needed?

2024-02-20 08:45 UTC, Hathoriel commented on src/service/rpc/utxo/DogeRpc.ts
> +export class DogeRpc extends AbstractDogeRpc implements DogeRpcSuite {
you are not using it. YOu are using DogeLoadBalancedRpc

2024-02-20 09:08 UTC, rostislavjadavan commented on src/service/rpc/utxo/DogeRpc.ts
> +export class DogeRpc extends AbstractDogeRpc implements DogeRpcSuite {
Right! Removed :)

2024-02-22 11:21 UTC, Hathoriel approved these changes

2024-02-22 11:21 UTC, merged