Multitoken tests
tatumio/tatum-js pull request #301
Opened 2022-01-13 17:33 UTC by jakcinmarina

2022-01-13 19:03 UTC, vlnevyhosteny requested changes

2022-01-17 08:07 UTC, jakcinmarina commented on packages/tatum-bsc/src/transaction/bsc.ts
> +  erc1155TokenABI,
yeah it was the reason tests failed for most chains. 
erc1155TokenABI was often used in code but wasn't imported at all

2022-01-17 08:09 UTC, jakcinmarina commented on packages/tatum-one/src/transaction/one.ts
> +  erc1155TokenABI,
wasn't initially imported but was used in code

2022-01-17 08:13 UTC, jakcinmarina commented on packages/tatum/src/multiToken/tests/celo.spec.ts
> +      expect(deployMultiTokenToken).not.toBeNull()
yeah, will fix that

2022-01-17 08:15 UTC, vlnevyhosteny commented on packages/tatum-bsc/src/transaction/bsc.ts
> +  erc1155TokenABI,
Weird :/

2022-02-02 15:32 UTC, closed without merging