Feature/solana migration
tatumio/tatum-js pull request #361
Opened 2022-02-04 12:21 UTC by jakcinmarina

2022-02-15 09:06 UTC, npwork commented on packages/blockchain/solana/src/lib/solana.sdk.ts
> +    api,
please remove api

2022-02-15 09:07 UTC, npwork commented on packages/blockchain/solana/src/lib/solana.sdk.ts
> +      getTransaction: BlockchainSolanaService.solanaGetTransaction,
I think there are more functions available in BlockchainSolanaService

2022-02-15 09:07 UTC, npwork commented on packages/blockchain/solana/src/lib/solana.sdk.ts
> +    blockchain: {
please add tests for mapping (check btc as an example)

2022-02-15 09:18 UTC, vlnevyhosteny requested changes

2022-02-16 15:03 UTC, jakcinmarina commented on packages/blockchain/solana/src/lib/schema/schema.ts
> +export const METADATA_SCHEMA = new Map<any, any>([
let's fix after release

2022-02-16 17:04 UTC, vlnevyhosteny approved these changes

2022-02-17 11:37 UTC, npwork commented
@jakcinmarina  please resolve conflicts

2022-02-17 12:20 UTC, jakcinmarina commented
updated

2022-02-17 12:33 UTC, merged