support tezos
tatumio/tatum-js pull request #39
Opened 2021-03-30 11:14 UTC by cuongnm1006

2021-04-25 13:29 UTC, tatumio requested changes

2021-04-25 13:29 UTC, tatumio commented on src/transaction/xtz.ts
> +  const url = testnet ? 'https://testnet-tezos.giganode.io' : 'https://mainnet-tezos.giganode.io';
Url should be set as a parameter.

2021-04-25 13:29 UTC, tatumio commented on src/wallet/wallet.ts
> +    return { xpub: seed.toString('hex'), mnemonic: mnem };
This cannot be xpub. Because it contains private keys inside. This must be derived path.

2021-04-25 13:29 UTC, tatumio commented on src/wallet/address.ts
> +    const privateKey = await b58cencode(key, prefix.edsk2);
Public address cannot be derived from private key in our architecture

2021-04-26 10:46 UTC, linhdangkk commented on src/transaction/xtz.ts
> +  const url = testnet ? 'https://testnet-tezos.giganode.io' : 'https://mainnet-tezos.giganode.io';
Fixed

2022-08-05 21:46 UTC, closed without merging