Feature/tt 33 gas pump
tatumio/tatum-js pull request #590
Opened 2022-09-09 16:33 UTC by opefago

Added abi for V2 Custodial Wallet Factory V2

2022-09-09 19:10 UTC, samuelsramko requested changes
I am missing whole functionality about gas pump here - expecially createAddress - private key is required there, it must be part of SDK. Read operations could be obtained from the OpenAPI scheme and call API directly, but not those with private keys and tx signing

2022-09-09 19:10 UTC, samuelsramko commented on packages/shared/blockchain/evm-based/src/lib/services/evm-based.custodial.ts
> +export type CustodialChain = 'CELO' | 'TRON' | 'ONE' | 'XDC' | 'ETH' | 'MATIC' | 'KLAY' | 'BSC'
This should be GasPumpChain

2022-09-16 06:41 UTC, samuelsramko requested changes
We need to wait for final version of a gas pump contract to include the ABI and bytecode here

2022-09-16 06:41 UTC, samuelsramko commented on packages/shared/blockchain/evm-based/src/lib/services/evm-based.gas.pump.ts
> +            ? '0x909ec0d70a4dA19848F6678e8a4478864dB94E0F'
use constants here and export them

2022-09-16 09:43 UTC, Hathoriel commented on packages/blockchain/celo/src/lib/services/celo.tx.ts
> +        broadcastFunction: BnbSmartChainService.bscBroadcast,
In celo you have bscBroadcast?

2022-09-16 09:43 UTC, Hathoriel commented on packages/blockchain/polygon/src/lib/services/polygon.tx.ts
> +        broadcastFunction: BnbSmartChainService.bscBroadcast,
again in polygon bscBroadcast

2022-09-19 07:52 UTC, samuelsramko commented on packages/shared/blockchain/evm-based/src/lib/services/evm-based.gas.pump.ts
> +          return testnet ? ONE_TESTNET_CUSTODIAL_FACTORY_V2 : ONE_MAINNET_CUSTODIAL_FACTORY_V2
on testnet, you should throw - its not supported for now

2022-09-19 10:17 UTC, samuelsramko commented on packages/shared/blockchain/evm-based/src/lib/services/evm-based.gas.pump.ts
> +export const ETH_MAINNET_CUSTODIAL_FACTORY_V2 = '0x5975906E29214339CC6D292cD6101C68f8de01e4'
this is not correct address - you have switched with testnet one @opefago

2023-03-23 12:17 UTC, closed without merging