Feature/tt 610 sdk bnb
tatumio/tatum-js pull request #637
Opened 2022-10-31 07:57 UTC by jhammer-tatum

2022-11-03 09:03 UTC, samuelsramko requested changes

2022-11-03 09:03 UTC, samuelsramko commented on packages/blockchain/bnb/src/lib/services/bnb.tx.ts
> +    return ApiServices.blockchain.bnb.bnbBroadcast({
you should wrap with if (body.signatureId) ApiServices.blockchain.bnb.sendTransaction) else this

2022-11-03 09:03 UTC, samuelsramko commented on packages/blockchain/bnb/src/lib/services/bnb.tx.ts
> +    prepareTransaction,
missing JS Doc with texts and descriptions

2022-11-06 13:27 UTC, alexloiko commented on packages/blockchain/bnb/src/lib/services/bnb.tx.ts
> +      return ApiServices.blockchain.bnb.bnbBlockchainTransfer(body as any)
please do not use cast to any

2022-11-06 13:28 UTC, alexloiko commented on examples/bnb-example/src/app/bnb.tx.example.ts
> +  const bnbSDK = TatumBnbSDK({ apiKey: 'PLACE-YOUR-API-KEY-HERE' })
we've discussed to place this key everywhere '75ea3138-d0a1-47df-932e-acb3ee807dab' in examples

2022-11-06 13:29 UTC, alexloiko commented on examples/bnb-example/src/app/bnb.wallet.example.ts
> +  console.log(` My public address is ${address}, with private key ${privateKey}.`)
minor. excessive space in comment

2022-11-06 13:30 UTC, alexloiko commented on packages/api-client/src/generated/core/OpenAPI.ts
> +import type { ApiRequestOptions } from './ApiRequestOptions'
changes in generated files

2022-11-06 13:32 UTC, alexloiko commented on packages/blockchain/bnb/src/lib/services/bnb.kms.ts
> +      ? provider
please avoid double chaining of in-place ifs

2022-11-06 13:34 UTC, alexloiko commented on packages/blockchain/bnb/src/lib/services/bnb.tx.ts
> +      if ((e as any).code === SdkErrorCode.INSUFFICIENT_FUNDS) {
please avoid cast to any

2022-11-07 17:05 UTC, merged