BTC finalization - add examples
tatumio/tatum-js pull request #647
Opened 2022-11-02 16:31 UTC by pedrodbaptista

2022-11-03 08:17 UTC, samuelsramko requested changes

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/README.md
> +- assign deposit address to virtual account
not assign, but generate - we are generating, not assigning - its different operation

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/README.md
> +console.log(`Mnemonic: ${mnemonic} - xpub: ${xpub}`)
address and private key should be here as well to generate 1 final address

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/src/app/btc.kms.example.ts
>  export async function btcKmsExample() {
kms examples should not be there - delete the file pls

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/src/app/btc.virtualAccount.example.ts
> +  const btcSDK = TatumBtcSDK({ apiKey: REPLACE_ME_WITH_TATUM_API_KEY })
use real FREE testnet API Key instead of a placeholder - check XLM or XRP

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/src/app/btc.virtualAccount.example.ts
> +  const address = await btcSDK.virtualAccount.depositAddress.create('5e68c66581f2ee32bc354087', 1)
you must first create wallet, xpub, virtual account and then generate deposit address - full flow must be there

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/src/app/btc.virtualAccount.example.ts
> +  await btcSDK.virtualAccount.storeTokenAddress('7c21ed165e294db78b95f0f181086d6f', 'MY_TOKEN')
this is stupidity - its not supported for BTC

2022-11-03 08:17 UTC, samuelsramko commented on examples/btc-example/src/app/btc.virtualAccount.example.ts
> +  const withdrawals = await btcSDK.virtualAccount.withdrawal.getAll('Done')
this doesnt have to be here - check other examples of virtual accounts

2022-11-03 08:17 UTC, samuelsramko commented on packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
> +  const getChain = (type: string) => {
we should return Currency.BTC/LTC, not strings

2022-11-03 08:17 UTC, samuelsramko commented on packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
> +    totalBalance = balances.reduce(
this could be const

2022-11-03 08:17 UTC, samuelsramko commented on packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
> +    const totalBalance = utxos.reduce((sum, u) => sum + u.value, 0)
I would wrap u.value in bigNumber to avoid string instead of number - in general, everywhere

2022-11-03 11:12 UTC, samuelsramko commented
@pedrodbaptista still some unresolved comments

2022-11-03 13:07 UTC, pedrodbaptista commented on packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
> +    totalBalance = balances.reduce(
Sorry wasn't finished.

2022-11-06 14:38 UTC, samuelsramko approved these changes

2022-11-06 14:38 UTC, merged