Added Cardano offchain integration
tatumio/tatum-js pull request #68
Opened 2021-06-17 12:58 UTC by Hathoriel

2021-06-18 16:46 UTC, Hathoriel commented on src/transaction/ada.ts
> +    Buffer.from(privateKey, 'hex'),
@samuelsramko Why I need a here private key? In the case of BTC, this doesn't need the private key. With this setup, I am not able to create a transaction and sign it later. Please propose some workaround.

2021-06-21 06:39 UTC, samuelsramko requested changes

2021-06-21 06:39 UTC, samuelsramko commented on src/transaction/ada.ts
> +  for (const to of tos) {
do the whole calculation in BigNumber. let amount = new BigNumber(0)...

2021-06-21 06:39 UTC, samuelsramko commented on src/transaction/ada.ts
> +    for (const utxo of utxos) {
use BigNumber()

2021-06-21 06:39 UTC, samuelsramko commented on src/transaction/ada.ts
> +  let amount = 0
use BigNumber

2021-06-21 07:54 UTC, samuelsramko approved these changes

2021-06-21 07:57 UTC, merged